title: Documentation
description: A set of documents describing the implementation of carbon monitoring in the Ada Platform.
remote_theme: just-the-docs/just-the-docs@v0.10.1

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-remote-theme

search_enabled: true
color_scheme: dark

mermaid:
  version: "10.9.1"

url: "https://prodmodfour.github.io"
baseurl: "/Ada_Carbon_Monitoring_Implementation_Documentation"